"""Tests for the gateway container entrypoint.

The entrypoint is a Bash script (`entrypoint.sh`) that runs at
container start. It does the things a container can't ask the user to
do interactively: ensure data directories exist, autogenerate a
bearer token on first boot, mint a self-signed TLS cert if none is
provided, render `gateway.toml` from env vars, then exec the gateway
binary.

Tests are driven through env-var overrides:
    DATA_DIR        — root of the persistent volume (default /data)
    GEN_CONFIG_PATH — gen_config.py location (default /opt/gen_config.py)
    GATEWAY_BIN     — gateway binary (default /usr/local/bin/music-gateway)

Each test injects a temp dir for DATA_DIR and a stub gateway script
that records argv + env and exits 0. The entrypoint runs to
completion in the test, which lets us assert on the side effects
(directories created, files persisted, gateway invoked with the
right config path).
"""

from __future__ import annotations

import os
import stat
import subprocess
import tomllib
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
ENTRYPOINT = REPO_ROOT / "docker" / "gateway" / "entrypoint.sh"
GEN_CONFIG = REPO_ROOT / "docker" / "gateway" / "gen_config.py"


def _stub_gateway(tmp_path: Path) -> Path:
    """A fake `music-gateway` binary that records its invocation.

    Writes `argv\\n<env-dump>` to `tmp_path/gateway.invoked`. Exits 0
    so the entrypoint's `exec` reports success."""
    bin_path = tmp_path / "music-gateway"
    bin_path.write_text(
        '#!/usr/bin/env bash\n'
        f'echo "$@" > "{tmp_path}/gateway.invoked"\n'
        'exit 0\n'
    )
    bin_path.chmod(0o755)
    return bin_path


def _base_env(tmp_path: Path) -> dict[str, str]:
    """Minimum env for a successful entrypoint run."""
    return {
        "PATH": os.environ["PATH"],
        "DATA_DIR": str(tmp_path / "data"),
        "GEN_CONFIG_PATH": str(GEN_CONFIG),
        "GATEWAY_BIN": str(_stub_gateway(tmp_path)),
        "NAVIDROME_URL": "http://nav.lan:4533",
        "NAVIDROME_USERNAME": "alice",
        "NAVIDROME_PASSWORD": "wonderland",
    }


def _run(env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(ENTRYPOINT)],
        env=env,
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )


def test_creates_data_subdirectories(tmp_path: Path) -> None:
    env = _base_env(tmp_path)
    result = _run(env)
    assert result.returncode == 0, result.stderr

    data = tmp_path / "data"
    for sub in ("state", "certs", "audio", "config"):
        assert (data / sub).is_dir(), f"{sub} not created"


def test_generates_bearer_token_on_first_boot(tmp_path: Path) -> None:
    env = _base_env(tmp_path)
    # Note: GATEWAY_BEARER_TOKEN deliberately unset.
    result = _run(env)
    assert result.returncode == 0, result.stderr

    token_file = tmp_path / "data" / "state" / "bearer.token"
    assert token_file.is_file(), "bearer.token not persisted"

    token = token_file.read_text().strip()
    # 32 bytes hex-encoded → 64 chars. Allow any hex-ish length ≥ 32
    # so the assertion isn't brittle to the openssl-rand variant used.
    assert len(token) >= 32, f"token too short: {token!r}"

    # Token file must be readable only by the owner — refresh tokens
    # ride on this secret.
    mode = stat.S_IMODE(token_file.stat().st_mode)
    assert mode == 0o600, f"bearer.token mode is {oct(mode)}"


def test_reuses_persisted_bearer_token(tmp_path: Path) -> None:
    """Second boot must NOT mint a new token — that would invalidate
    every device's stored bearer."""
    env = _base_env(tmp_path)
    assert _run(env).returncode == 0

    token_file = tmp_path / "data" / "state" / "bearer.token"
    first = token_file.read_text()

    assert _run(env).returncode == 0
    second = token_file.read_text()

    assert first == second


def test_env_bearer_token_takes_precedence(tmp_path: Path) -> None:
    """If the operator sets the env var, persist it as the
    canonical value rather than the autogenerated one."""
    env = _base_env(tmp_path)
    env["GATEWAY_BEARER_TOKEN"] = "deadbeef" * 8
    assert _run(env).returncode == 0

    persisted = (tmp_path / "data" / "state" / "bearer.token").read_text().strip()
    assert persisted == "deadbeef" * 8


def test_self_signed_cert_generated_when_absent(tmp_path: Path) -> None:
    env = _base_env(tmp_path)
    assert _run(env).returncode == 0

    cert = tmp_path / "data" / "certs" / "gateway.local.pem"
    key = tmp_path / "data" / "certs" / "gateway.local-key.pem"
    assert cert.is_file()
    assert key.is_file()

    # Sanity-check the PEM headers — proves we generated something
    # parseable, not just a placeholder file.
    assert "BEGIN CERTIFICATE" in cert.read_text()
    assert "PRIVATE KEY" in key.read_text()


def test_existing_cert_not_overwritten(tmp_path: Path) -> None:
    """Cert rotation is an operator concern, not the entrypoint's."""
    env = _base_env(tmp_path)
    certs = tmp_path / "data" / "certs"
    certs.mkdir(parents=True)
    sentinel = "MOUNTED-NOT-GENERATED"
    (certs / "gateway.local.pem").write_text(sentinel)
    (certs / "gateway.local-key.pem").write_text(sentinel)

    assert _run(env).returncode == 0
    assert (certs / "gateway.local.pem").read_text() == sentinel
    assert (certs / "gateway.local-key.pem").read_text() == sentinel


def test_renders_config_toml(tmp_path: Path) -> None:
    env = _base_env(tmp_path)
    env["EMBEDDER_URL"] = "http://embedder:9000"
    assert _run(env).returncode == 0

    cfg_path = tmp_path / "data" / "config" / "gateway.toml"
    assert cfg_path.is_file()
    parsed = tomllib.loads(cfg_path.read_text())
    assert parsed["upstream"]["navidrome_url"] == "http://nav.lan:4533"
    assert parsed["embedder"]["url"] == "http://embedder:9000"


def test_invokes_gateway_with_config_path(tmp_path: Path) -> None:
    env = _base_env(tmp_path)
    assert _run(env).returncode == 0

    invocation = (tmp_path / "gateway.invoked").read_text().strip()
    cfg_path = str(tmp_path / "data" / "config" / "gateway.toml")
    assert invocation == f"--config {cfg_path}"


def test_fails_fast_on_missing_required_env(tmp_path: Path) -> None:
    """gen_config exits non-zero → entrypoint must not exec the
    gateway with a broken/empty config."""
    env = _base_env(tmp_path)
    del env["NAVIDROME_URL"]
    result = _run(env)
    assert result.returncode != 0
    assert not (tmp_path / "gateway.invoked").exists()
