[package]
name = "music-player"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
music-core = { workspace = true }
music-cache = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
rodio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
