#!/usr/bin/env bash
#
# Gateway container entrypoint.
#
# Translates environment-variable input into the file-and-process
# state the gateway expects:
#
#   1. Ensure /data subdirectories exist.
#   2. Resolve a bearer token: env > persisted file > autogenerated.
#      Persist whichever wins so reboots are deterministic.
#   3. Generate a self-signed TLS cert if no cert is already mounted.
#   4. Default the SQLite state/cache paths under /data/state.
#   5. Render gateway.toml via gen_config.py.
#   6. exec the gateway binary.
#
# Behaviour is parameterised through env so tests can run it against
# a temp dir and a stub binary:
#
#   DATA_DIR         persistent volume root        (default /data)
#   GEN_CONFIG_PATH  templater script              (default /opt/gateway/gen_config.py)
#   GATEWAY_BIN      gateway binary                (default /usr/local/bin/music-gateway)
#   GATEWAY_HOSTNAME hostname for the SAN          (default gateway.local)

set -euo pipefail

DATA_DIR="${DATA_DIR:-/data}"
GEN_CONFIG_PATH="${GEN_CONFIG_PATH:-/opt/gateway/gen_config.py}"
GATEWAY_BIN="${GATEWAY_BIN:-/usr/local/bin/music-gateway}"
GATEWAY_HOSTNAME="${GATEWAY_HOSTNAME:-gateway.local}"

# 1. Directory layout.
mkdir -p \
    "$DATA_DIR/state" \
    "$DATA_DIR/certs" \
    "$DATA_DIR/audio" \
    "$DATA_DIR/config"

# 2. Bearer token.
#
# Three sources, in priority order:
#   a. GATEWAY_BEARER_TOKEN in env → operator-provided. Persist so
#      `cat bearer.token` matches what clients are using.
#   b. /data/state/bearer.token from a previous boot.
#   c. None of the above → generate one, persist, log nothing (it's
#      a secret).
TOKEN_FILE="$DATA_DIR/state/bearer.token"
umask 077
if [ -n "${GATEWAY_BEARER_TOKEN:-}" ]; then
    printf '%s\n' "$GATEWAY_BEARER_TOKEN" > "$TOKEN_FILE"
elif [ -f "$TOKEN_FILE" ]; then
    GATEWAY_BEARER_TOKEN="$(head -n1 "$TOKEN_FILE")"
    export GATEWAY_BEARER_TOKEN
else
    GATEWAY_BEARER_TOKEN="$(openssl rand -hex 32)"
    export GATEWAY_BEARER_TOKEN
    printf '%s\n' "$GATEWAY_BEARER_TOKEN" > "$TOKEN_FILE"
fi
chmod 600 "$TOKEN_FILE"

# 3. TLS.
#
# Self-sign only when neither cert nor key is present. Mounting a
# real cert (Let's Encrypt, mkcert, internal CA) is the recommended
# production path — this branch exists so first-boot doesn't fail.
CERT_FILE="$DATA_DIR/certs/gateway.local.pem"
KEY_FILE="$DATA_DIR/certs/gateway.local-key.pem"
export GATEWAY_TLS_CERT="${GATEWAY_TLS_CERT:-$CERT_FILE}"
export GATEWAY_TLS_KEY="${GATEWAY_TLS_KEY:-$KEY_FILE}"

if [ ! -f "$GATEWAY_TLS_CERT" ] || [ ! -f "$GATEWAY_TLS_KEY" ]; then
    echo "entrypoint: minting self-signed TLS cert for ${GATEWAY_HOSTNAME}" >&2
    openssl req -x509 -newkey rsa:2048 -nodes \
        -days 825 \
        -keyout "$GATEWAY_TLS_KEY" \
        -out "$GATEWAY_TLS_CERT" \
        -subj "/CN=${GATEWAY_HOSTNAME}" \
        -addext "subjectAltName=DNS:${GATEWAY_HOSTNAME},DNS:localhost,IP:127.0.0.1" \
        >/dev/null 2>&1
fi

# 4. SQLite paths default under /data/state. Operators can override
#    by setting GATEWAY_STATE_DB / GATEWAY_CACHE_DB in the env.
export GATEWAY_STATE_DB="${GATEWAY_STATE_DB:-$DATA_DIR/state/gateway-state.sqlite}"
export GATEWAY_CACHE_DB="${GATEWAY_CACHE_DB:-$DATA_DIR/state/gateway-cache.sqlite}"

# 5. Render gateway.toml. gen_config.py exits non-zero on bad input,
#    which `set -e` propagates — no need to check explicitly.
CONFIG_FILE="$DATA_DIR/config/gateway.toml"
python3 "$GEN_CONFIG_PATH" "$CONFIG_FILE"

# 6. Hand off to the gateway. `exec` so the gateway becomes PID 1
#    (or whatever the supervisor passed us as), receiving signals
#    directly.
exec "$GATEWAY_BIN" --config "$CONFIG_FILE"
