// Crate digging — the visual album explorer. Albums are sorted into
// crates (decade / genre / artist / playlist / random) and rendered as
// LPs in a box the user digs through one by one: wheel or arrow keys on
// desktop, vertical swipe on touch. The neighboring crates sit small and
// dimmed to the left/right of the active one — click them or swipe the
// stage horizontally to move; the full crate list lives in a rail on the
// right.
//
// decade/genre/artist/random regroup the same cached listAllAlbums()
// result — pure client-side work. playlist additionally fetches each
// playlist's tracks (lazily, only when that sort is selected) to map
// them onto catalog albums. The page tint follows the record in your
// hand: the focused album's cover drives the existing --art-* pipeline.

import { useQuery } from "@tanstack/react-query";
import { Play } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { coverArtUrl, listAllAlbums } from "../api/client";
import { getPlaylist, listPlaylists } from "../api/playlists";
import { Layout } from "../components/Layout";
import {
  useCoverPalette,
  type Palette,
} from "../components/ArtworkPalette";
import {
  buildCrates,
  buildPlaylistCrates,
  CRATE_SORTS,
  type Crate,
  type CrateSort,
  type PlaylistAlbums,
} from "../crates/buildCrates";
import { CrateDigger } from "../crates/CrateDigger";
import { CratePreview, CratePreviewSpacer } from "../crates/CratePreview";
import { Link, useRoute } from "../router";
import { usePlayback } from "../sync/usePlayback";

const SORT_LABEL: Record<CrateSort, string> = {
  decade: "decade",
  genre: "genre",
  artist: "artist",
  playlist: "playlist",
  random: "random",
};

function sortFromSearch(search: string): CrateSort {
  const raw = new URLSearchParams(search).get("sort");
  return (CRATE_SORTS as readonly string[]).includes(raw ?? "")
    ? (raw as CrateSort)
    : "decade";
}

// Each playlist reduced to the album ids of its tracks, in playlist
// order. getPlaylist hydrates tracks via the catalog, so this is N
// requests per playlist — which is why it's gated behind the sort
// actually being selected, and cached for the session.
async function fetchPlaylistAlbums(): Promise<PlaylistAlbums[]> {
  const summaries = await listPlaylists();
  const settled = await Promise.allSettled(
    summaries.map((s) => getPlaylist(s.id)),
  );
  return settled
    .filter(
      (r): r is PromiseFulfilledResult<Awaited<ReturnType<typeof getPlaylist>>> =>
        r.status === "fulfilled",
    )
    .map((r) => ({
      id: r.value.playlist.id,
      name: r.value.playlist.name,
      albumIds: r.value.tracks.flatMap((t) => (t.albumId ? [t.albumId] : [])),
    }));
}

export function Crates() {
  const { search, navigate } = useRoute();
  const sort = sortFromSearch(search);
  const { playAlbum } = usePlayback();

  // Same query key + fn as the Albums "all" view, so the two pages share
  // one cache entry — whichever loads first pays the pagination cost.
  const q = useQuery({
    queryKey: ["albums", "alphabeticalByName", "all"],
    queryFn: () => listAllAlbums("alphabeticalByName"),
    staleTime: 60_000,
  });

  const playlistsQ = useQuery({
    queryKey: ["crates", "playlist-albums"],
    queryFn: fetchPlaylistAlbums,
    enabled: sort === "playlist",
    staleTime: 5 * 60_000,
  });

  // The shuffle seed is page state: stable across re-renders (so digging
  // doesn't reshuffle under you), regenerated by re-clicking "random".
  const [randomSeed, setRandomSeed] = useState(
    () => Math.floor(Math.random() * 2 ** 31) || 1,
  );

  const crates = useMemo(() => {
    if (sort === "playlist") {
      return buildPlaylistCrates(playlistsQ.data ?? [], q.data ?? []);
    }
    return buildCrates(q.data ?? [], sort, randomSeed);
  }, [q.data, playlistsQ.data, sort, randomSeed]);

  // Position state. The sort key partitions crate/dig positions: changing
  // sort resets to the first crate, and each crate remembers where you
  // left off digging (keyed by crate id) for the session.
  const [pos, setPos] = useState<{ sort: CrateSort; crateIdx: number }>({
    sort,
    crateIdx: 0,
  });
  // Which side the current crate was entered from — drives the digger's
  // slide-in (it remounts per crate via key, so the animation replays).
  const [slideDir, setSlideDir] = useState<1 | -1 | 0>(0);
  const digMemory = useRef(new Map<string, number>());
  const crateIdx =
    pos.sort === sort ? Math.min(pos.crateIdx, Math.max(0, crates.length - 1)) : 0;
  const crate: Crate | undefined = crates[crateIdx];
  const prevCrate: Crate | undefined = crates[crateIdx - 1];
  const nextCrate: Crate | undefined = crates[crateIdx + 1];
  const [digRaw, setDigRaw] = useState(0);
  const digIdx = crate
    ? Math.min(crate.albums.length - 1, Math.max(0, digRaw))
    : 0;

  function selectCrate(nextIdx: number) {
    if (!crates.length) return;
    const clamped = Math.max(0, Math.min(crates.length - 1, nextIdx));
    if (crate) digMemory.current.set(crate.id, digIdx);
    setSlideDir(clamped > crateIdx ? 1 : clamped < crateIdx ? -1 : 0);
    setPos({ sort, crateIdx: clamped });
    const next = crates[clamped];
    setDigRaw(next ? (digMemory.current.get(next.id) ?? 0) : 0);
  }

  function setSort(next: CrateSort) {
    // Re-clicking "random" reshuffles — that's the point of the crate.
    if (next === sort && next !== "random") return;
    if (next === "random") setRandomSeed(Math.floor(Math.random() * 2 ** 31) || 1);
    if (crate) digMemory.current.set(crate.id, digIdx);
    navigate(`/crates?sort=${next}`);
    setSlideDir(0);
    setPos({ sort: next, crateIdx: 0 });
    setDigRaw(0);
  }

  // Keep the rail's active row in view when crates change via swipe.
  const railRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    railRef.current
      ?.querySelector('[aria-selected="true"]')
      ?.scrollIntoView({ block: "nearest" });
  }, [crateIdx, sort]);

  const focused = crate?.albums[digIdx];
  // Size 300 matches the sleeve <img>, so the palette extraction reads
  // the cover straight from the browser cache instead of refetching a
  // larger variant.
  const cover = focused ? coverArtUrl(focused.coverArt, 300, focused.name) : null;
  const palette = useCoverPalette(cover);
  // Hold the last extracted palette while the next one is in flight —
  // otherwise every dig step drops the --art-* tint for the fetch+extract
  // window and the background flashes untinted.
  const lastPalette = useRef<Palette | null>(null);
  if (palette) lastPalette.current = palette;
  const heldPalette = palette ?? lastPalette.current;

  const loading = q.isLoading || (sort === "playlist" && playlistsQ.isLoading);
  const error = q.error ?? (sort === "playlist" ? playlistsQ.error : null);

  return (
    <Layout
      breadcrumb={crate ? `crates · ${crate.label}` : "crates"}
      palette={heldPalette}
    >
      <div className="section">
        <div className="section-head">
          <h2>crates</h2>
          {crates.length > 0 && (
            <span className="count tabular">
              {crates.length} crates ·{" "}
              {crates.reduce((n, c) => n + c.albums.length, 0)} records
            </span>
          )}
          <div className="crate-controls">
            <div className="crate-seg" role="group" aria-label="sort crates by">
              {CRATE_SORTS.map((s) => (
                <button
                  key={s}
                  type="button"
                  className={`crate-seg-btn ${s === sort ? "is-active" : ""}`}
                  aria-pressed={s === sort}
                  onClick={() => setSort(s)}
                >
                  {SORT_LABEL[s]}
                </button>
              ))}
            </div>
          </div>
        </div>

        {loading && <p className="text-fg-muted text-sm">loading the crates…</p>}
        {error != null && (
          <p className="text-danger text-sm">
            error: {(error as Error).message}
          </p>
        )}
        {!loading && error == null && crates.length === 0 && (
          <p className="text-fg-muted text-sm">
            {sort === "playlist"
              ? "no playlists with catalog albums yet."
              : "no albums to dig through."}
          </p>
        )}

        {crate && (
          <div className="crate-floor">
            <div className="crate-main">
              <div className="crate-carousel">
                {prevCrate ? (
                  <CratePreview
                    key={prevCrate.id}
                    crate={prevCrate}
                    side="left"
                    onSelect={() => selectCrate(crateIdx - 1)}
                  />
                ) : (
                  <CratePreviewSpacer side="left" />
                )}
                <CrateDigger
                  key={crate.id}
                  albums={crate.albums}
                  label={crate.label}
                  index={digIdx}
                  onIndexChange={setDigRaw}
                  onOpen={(album) => navigate(`/albums/${album.id}`)}
                  onCrateStep={(dir) => selectCrate(crateIdx + dir)}
                  hasPrevCrate={!!prevCrate}
                  hasNextCrate={!!nextCrate}
                  enterFrom={slideDir}
                />
                {nextCrate ? (
                  <CratePreview
                    key={nextCrate.id}
                    crate={nextCrate}
                    side="right"
                    onSelect={() => selectCrate(crateIdx + 1)}
                  />
                ) : (
                  <CratePreviewSpacer side="right" />
                )}
              </div>

              {focused && (
                <div className="crate-meta">
                  <Link to={`/albums/${focused.id}`} className="crate-meta-title">
                    {focused.name}
                  </Link>
                  <div className="crate-meta-sub">
                    {focused.artistId && focused.artist ? (
                      <Link to={`/artists/${focused.artistId}`}>
                        {focused.artist}
                      </Link>
                    ) : (
                      <span>{focused.artist ?? "unknown artist"}</span>
                    )}
                    {focused.year != null && focused.year > 0 && (
                      <span className="tabular"> · {focused.year}</span>
                    )}
                    {focused.genre && <span> · {focused.genre}</span>}
                    {focused.songCount != null && (
                      <span className="tabular">
                        {" "}
                        · {focused.songCount} tracks
                      </span>
                    )}
                  </div>
                  <button
                    type="button"
                    className="play-disc crate-meta-play"
                    aria-label={`play ${focused.name}`}
                    onClick={() => void playAlbum(focused.id)}
                  >
                    <Play size={18} fill="currentColor" strokeWidth={0} />
                  </button>
                </div>
              )}
            </div>

            <div
              ref={railRef}
              className="crate-rail"
              role="listbox"
              aria-label="crates"
            >
              {crates.map((c, i) => (
                <button
                  key={c.id}
                  type="button"
                  role="option"
                  aria-selected={i === crateIdx}
                  className={`crate-rail-item ${i === crateIdx ? "is-active" : ""}`}
                  onClick={() => selectCrate(i)}
                >
                  <span className="crate-rail-label">{c.label}</span>
                  <span className="crate-rail-count tabular">
                    {c.albums.length}
                  </span>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
